# Generated by Django 5.0.6 on 2024-07-03 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dealerprofile_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='core.dealership'),
        ),
    ]
