# Generated by Django 5.0.6 on 2024-07-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dealerprofile_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='dealerships',
            field=models.ManyToManyField(blank=True, related_name='dealer_profiles', to='core.dealership'),
        ),
    ]
