# Generated by Django 5.0.6 on 2024-07-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wholesalerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wholesalerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
