# Generated by Django 5.0.6 on 2024-07-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_appraisal_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
