# Generated by Django 5.0.6 on 2024-07-09 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_appraisal_last_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='sent_to_management',
            field=models.ManyToManyField(blank=True, related_name='appraisals_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
