# Generated by Django 5.0.6 on 2024-07-11 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_appraisal_general_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprofile',
            name='dealerships',
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='management_dealers',
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='sales_dealers',
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profiles', to='core.dealership'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='dealers',
            field=models.ManyToManyField(blank=True, related_name='dealerships', through='core.DealerProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
