# Generated by Django 5.0.6 on 2024-07-11 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_dealerprofile_dealerships_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprofile',
            name='dealership',
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='dealers',
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='dealerships',
            field=models.ManyToManyField(blank=True, related_name='dealer_profiles', to='core.dealership'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='management_dealers',
            field=models.ManyToManyField(blank=True, related_name='managed_dealerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealership',
            name='sales_dealers',
            field=models.ManyToManyField(blank=True, related_name='sales_dealerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
