# Generated by Django 5.0.6 on 2024-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='general_comments',
            field=models.ManyToManyField(blank=True, related_name='appraisal_general_comments', to='core.comment'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='private_comments',
            field=models.ManyToManyField(blank=True, related_name='appraisal_private_comments', to='core.comment'),
        ),
    ]
