# Generated by Django 5.0.6 on 2024-07-16 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_wholesalerprofile_is_wholesaler_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='comment_date_time',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='general_comments',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='private_comments',
        ),
        migrations.RemoveField(
            model_name='wholesalerprofile',
            name='is_wholesaler',
        ),
        migrations.AddField(
            model_name='comment',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.appraisal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='vehicle_photos',
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_description', models.TextField()),
                ('damage_location', models.CharField(max_length=100)),
                ('repair_cost_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='core.appraisal')),
                ('damage_photos', models.ManyToManyField(blank=True, related_name='damage_photos', to='core.photo')),
            ],
        ),
        migrations.AddField(
            model_name='appraisal',
            name='vehicle_photos',
            field=models.ManyToManyField(blank=True, related_name='vehicle_photos', to='core.photo'),
        ),
    ]
