# Generated by Django 5.0.6 on 2024-07-16 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_appraisal_comment_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='appraisal',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.appraisal'),
            preserve_default=False,
        ),
    ]
