# Generated by Django 5.0.6 on 2024-07-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_comment_appraisal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='damage_description',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='damage_location',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='damage_photos',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='repair_cost_estimate',
        ),
    ]
