# Generated by Django 5.0.6 on 2024-07-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_friendrequest_reciever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='reciever',
        ),
    ]
