# Generated by Django 5.0.6 on 2024-07-19 01:38

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_friendrequest_reciever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='dealership',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='core.dealership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='wholesaler_sender',
            field=models.ForeignKey(default=core.models.default_wholesaler, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='core.wholesalerprofile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
