# Generated by Django 5.0.6 on 2024-07-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_friendrequest_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
    ]
