# Generated by Django 5.0.6 on 2024-07-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_friendrequest_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='wholesaler_sender',
            new_name='sender',
        ),
    ]
