# Generated by Django 5.0.6 on 2024-07-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_wholesaler_sender_friendrequest_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='adjusted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wholesalerprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='core.wholesalerprofile'),
        ),
    ]
