# Generated by Django 5.0.6 on 2024-07-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_offer_adjusted_amount_wholesalerprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
