# Generated by Django 5.0.6 on 2024-07-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_offer_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='recipient_wholesaler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='core.wholesalerprofile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='core.dealership'),
        ),
    ]
