# Generated by Django 5.0.6 on 2024-07-22 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_friendrequest_recipient_wholesaler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.appraisal')),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_invites', to='core.wholesalerprofile')),
            ],
            options={
                'unique_together': {('appraisal', 'wholesaler')},
            },
        ),
        migrations.AddField(
            model_name='appraisal',
            name='invited_wholesalers',
            field=models.ManyToManyField(blank=True, related_name='invited_appraisals', through='core.AppraisalInvite', to='core.wholesalerprofile'),
        ),
    ]
