# Generated by Django 5.0.6 on 2024-07-23 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_appraisalinvite_appraisal_invited_wholesalers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='winner',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_appraisal', to='core.offer'),
        ),
    ]
