# Generated by Django 5.0.6 on 2024-07-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_offer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='ready_for_management',
            field=models.BooleanField(default=False),
        ),
    ]
