# Generated by Django 5.0.6 on 2024-07-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_appraisal_ready_for_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='vehicle_photos',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='damage_description',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='damage_location',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='damage_photos',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.AddField(
            model_name='damage',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='damage',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='damage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.damage'),
            preserve_default=False,
        ),
    ]
