# Generated by Django 5.0.6 on 2024-07-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_dealership_temporary_wholesalers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='wholesalers',
        ),
    ]
