# Generated by Django 5.0.6 on 2024-07-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_dealership_wholesalers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealership',
            old_name='temporary_wholesalers',
            new_name='wholesalers',
        ),
    ]
