# Generated by Django 5.0.6 on 2024-07-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_temporary_wholesalers_dealership_wholesalers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='wholesalers',
            field=models.ManyToManyField(blank=True, related_name='wholesaler_dealerships', to='core.wholesalerprofile'),
        ),
    ]
