# Generated by Django 5.0.6 on 2024-07-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_offer_temp_user_alter_offer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('appraisal', 'temp_user')},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
    ]
