# Generated by Django 5.0.6 on 2024-07-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_offer_unique_together_remove_offer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='temp_user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('appraisal', 'user')},
        ),
    ]
