# Generated by Django 5.0.6 on 2024-07-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename_temp_user_offer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='damage',
        ),
        migrations.AddField(
            model_name='damage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='damages/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
