# Generated by Django 5.0.6 on 2024-08-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_appraisal_sent_to_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesalerprofile',
            name='friends',
        ),
    ]
